name: la_curva
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
<<<<<<< HEAD
  intl: ^0.18.0
=======
>>>>>>> 639c5f13a27fd1e5c13a3de9f5da9a7cdcf3b36d

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
<<<<<<< HEAD
  assets:
    - assets/images/
  uses-material-design: true
 
  
=======
  uses-material-design: true
>>>>>>> 639c5f13a27fd1e5c13a3de9f5da9a7cdcf3b36d
