name: la_curva
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  intl: ^0.18.0
  image_picker: ^0.8.4+4
  flutter_paypal: ^0.2.0
  webview_flutter: ^4.0.0
  url_launcher: ^6.1.10
  uni_links: ^0.5.1
  mime: ^1.0.4
  http_parser: ^4.0.2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true


